# Generated by Django 4.2.5 on 2023-09-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToursProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название источника')),
                ('label', models.CharField(max_length=8, verbose_name='Лейбл источника')),
                ('base_url', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
